### ISSUE TITLE
Modern Responsive Redesign for FormById Component

### ISSUE THREAD

**Issue by priyam-03** [priyam-03/Recruitify#21]
# Beautify CSS for `FormById` Component - Modern, Responsive, and Scrollable

## Description
The `FormById` component requires an enhanced, modern design with a responsive layout. Key improvements:

## Key Enhancements

1. **Applicant Section**:
   - Improve spacing and ensure  responsiveness.
   - Enhance the layout for better readability.

2. **Job Description**:
   - Adjust font sizes and spacing for better readability.
   - Ensure responsiveness across different screen sizes.

3. **Buttons (Apply, Shortlist, Take Interview)**:
   - Add modern hover effects, rounded corners, and align buttons properly.
   - Ensure buttons are responsive and appropriately sized.

4. **Skills Scrolling**:
   - Improve the scrolling functionality with better navigation icons.
   - Add a smooth scroll effect for different sections seperately (Creator , Job description and applicants). 

## Deliverables
- Refactored `formById.module.css` with modern styles.
- Responsive design with scrollable sections.
- Improved button designs and hover effects.

**Comment by sairiteshdomakuntla** [comment]
Hii @priyam-03 .I would like to work on this issue.Can you please assign me this issue?

**Comment by priyam-03** [comment]
Okay sure.

**Comment by sairiteshdomakuntla** [comment]
> Okay sure.

iam unable to login or register your website

**Comment by priyam-03** [comment]
Are you using the deployed url or running locally?

**Comment by sairiteshdomakuntla** [comment]
> Are you using the deployed url or running locally?



yep, now it is coming in deployed one

**Comment by sairiteshdomakuntla** [comment]
> Are you using the deployed url or running locally?

but iam unable to do if i run locally

**Comment by priyam-03** [comment]
You need to provide env details, also you can connect with me by linkedin
or other way. We can further discuss there.

**Comment by sairiteshdomakuntla** [comment]
> You need to provide env details, also you can connect with me by linkedin or other way. We can further discuss there.

sure, we will connect through linkedin
