### ISSUE TITLE
Enhance UI/UX: Scrollable Sections, Fixed Buttons, and Aesthetic Improvements

### ISSUE THREAD

**Issue by priyam-03** [priyam-03/Recruitify#26]
### Description:
This issue aims to improve the user interface and experience by implementing a scrollable layout with fixed action buttons and enhancing the overall aesthetics of specific components.

### Requirements:
1. **Scrollable Layout with Fixed Buttons:**
   - The middle and right sections should be scrollable independently.
   - Keep the "Apply" button in the middle section fixed at the bottom of its section.

2. **Beautify CSS for Shortlist Modal:**
   - Improve the visual aesthetics of the shortlist modal to enhance user interaction and overall design appeal.

3. **Center Skills Section:**
   - Ensure that the skills section is always centered, rather than starting from the left. This will provide a more balanced and visually appealing layout.

**Comment by iblameRishi** [comment]
Hey @priyam-03 I'd like to work on this please!.

**Comment by priyam-03** [comment]
@iblameRishi if any doubt occurs you can mail me.

**Comment by priyam-03** [comment]
@iblameRishi any update?

**Comment by iblameRishi** [comment]
@priyam-03 really sorry but something came up, I wont be able to contribute. Sorry again!

**Comment by dwip708** [comment]
Hey @priyam-03 , I would like to work on these issues, and contribute to this project.

**Comment by priyam-03** [comment]
Okay if any doubt you can mail me.
