### ISSUE TITLE
Beautification of Shortlist Modal

### ISSUE THREAD

**Issue by priyam-03** [priyam-03/Recruitify#41]
#### Description:
The Shortlist Modal in `FormById` component needs visual enhancement and better color combinations for improved UI/UX.

#### Current:
- Basic UI with cramped elements.
- Minimal button styling.
- Lacks modal animations and background effects.
- No consistent or visually appealing color scheme.

![image](https://github.com/user-attachments/assets/3caa4e51-4f3e-4480-9b1e-3469e72d609d)

#### Expected:
- **Spacing**: Add consistent padding/margins between elements.
- **Buttons**: Improve hover effects, size, and contrast.
- **Modal**: Add shadow/blur effects, rounded corners, and smooth animations.
- **Color Scheme**: Use a better color palette with high contrast for text and buttons (e.g., soft background tones with vibrant accent colors like blue or green for buttons).

#### Steps to Reproduce:
1. Go to the Job Form by ID page.
2. Ensure you are the owner of the job post. (From your account job need to be created) 
3. Click on the **Shortlist** button to open the Shortlist Modal.
4. Observe the modal's UI and color scheme.
[Github Link](https://github.com/priyam-03/Recruitify/blob/main/frontend/src/shared/components/shortlistModal.js)

**Comment by Fahad-Ali-Khan-ca** [comment]
Hi, I would like to work on it

**Comment by priyam-03** [comment]
Okay sure. If any doubt occurs you can mail me.

**Comment by priyam-03** [comment]
@Fahad-Ali-Khan-ca  any updates?

**Comment by Fahad-Ali-Khan-ca** [comment]
Hi, priyam will update you soon

**Comment by priyam-03** [comment]
@Fahad-Ali-Khan-ca any update?

**Comment by Fahad-Ali-Khan-ca** [comment]
Hello Priyam,

Apologies for the delayed response! I was occupied with my midterm exams and couldn't address this sooner.

I have now created a PR that enhances the styling of the Shortlist Modal as requested. The PR includes improvements to padding, button styles, color scheme, and animations to create a more polished and accessible user experience.

Thank you for your patience, and please let me know if there are any further adjustments needed. I look forward to your feedback on the PR.
