### ISSUE TITLE
Modernize "Update Password" and "Update Profile" Pages CSS

### ISSUE THREAD

**Issue by priyam-03** [priyam-03/Recruitify#43]
#### Description:
The **Update Password** and **Update Profile** pages need a CSS overhaul for modernization. This includes better color combinations, an aesthetic redesign, and improved responsiveness across devices.

#### Current Behavior:
- The pages are functional but lack modern design elements.
- Color schemes, fonts, and layouts are outdated.
- Not fully responsive on mobile and smaller screens.

#### Expected Improvements:
1. **Color Scheme**: 
   - Use a clean and modern color palette. For example, soft background tones (light gray or pastel) paired with vibrant accents (navy blue, teal, or green) for buttons and headings.
   
2. **Typography**:
   - Enhance readability with larger font sizes, bolder headings, and consistent font families. A sans-serif font like Roboto or Open Sans would improve modern appeal.
   
3. **Layout & Spacing**:
   - Ensure consistent padding/margin around input fields, buttons, and page sections.
   - Add subtle shadow or border effects to form fields and buttons to make them stand out.
   
4. **Buttons**:
   - Update buttons with rounded corners, hover effects, and better color contrast.
   - Use transitions for smoother hover animations.
   
5. **Responsiveness**:
   - Ensure the pages are fully responsive across all screen sizes, especially mobile devices.
   - Adjust input fields, text, and buttons to scale appropriately for smaller screens.
   
#### Steps to Reproduce:
1. Go to the **Update Password** or **Update Profile** page.
2. Observe the current design, color schemes, and responsiveness.
   
#### Files Affected:
- [`UpdatePassword Page`](https://github.com/priyam-03/Recruitify/blob/main/frontend/src/screens/UpdatePasswordScreen.js)
- [ `UpdateProfile Page`](https://github.com/priyam-03/Recruitify/blob/main/frontend/src/screens/UpdateProfileScreen.js)

#### Additional Suggestions:
- Consider adding a progress bar or feedback for actions like password update success.
- Implement media queries for improved mobile responsiveness.
- Enhance form validation messages with clearer, modern styling (e.g., red error text, green success indicators).

**Comment by Shaunak-Gupta-dev** [comment]
i would like to try
can you assign this to me ....

**Comment by priyam-03** [comment]
Okay sure , if any doubt occurs you can mail me.

**Comment by Shaunak-Gupta-dev** [comment]
why did you unassign ?  ;(
