### ISSUE TITLE
 Modernizing Login/Signup Pages: Key Suggestions

### ISSUE THREAD

**Issue by priyam-03** [priyam-03/Recruitify#44]
### Current Challenges:
- Outdated design, color schemes, and fonts.
- Limited mobile responsiveness.

---

### 1. **Color Scheme**:
- Opt for a clean, modern background with vibrant accent colors for buttons and headings.
- Use color to subtly highlight input fields and form interactions.

### 2. **Typography**:
- Switch to modern, sans-serif fonts like Roboto or Open Sans.
- Increase heading sizes and ensure consistent font usage across the page.

### 3. **Layout & Spacing**:
- Ensure a clean, centered layout with ample padding around form fields and buttons.
- Add subtle shadows and borders for a modern touch.

### 4. **Buttons**:
- Introduce rounded corners, smooth hover effects, and larger, more accessible button sizes.
  
### 5. **Responsiveness**:
- Implement mobile-friendly designs, including full-width input fields and optimized scaling with media queries.

## Files :
[Login Page](https://github.com/priyam-03/Recruitify/blob/main/frontend/src/screens/LoginScreen.js)
[Sign Up Page](https://github.com/priyam-03/Recruitify/blob/main/frontend/src/screens/RegisterScreen.js)

## Additional Considerations:
- Add clear form validation messages and feedback.
- Optionally include progress indicators or loading animations for better user experience.

**Comment by Shaunak-Gupta-dev** [comment]
can you pls assign this to me ?

**Comment by prashantrai-30** [comment]
Hey @priyam-03,
can you please assign this to me :)

**Comment by Lafi-olfa** [comment]
can you please assign this to me ?

**Comment by priyam-03** [comment]
@prashantrai-30 you can work in this issue, if any doubt you can mail me.
