### ISSUE TITLE
Bug: I believe this is the logout button, but not visible

### ISSUE THREAD

**Issue by RohithNair27** [priyam-03/Recruitify#50]
Unable to log out because of this ( Responsive issue )

Kindly mark it as hacktober and assign it to me.
Also what is the set procedure, can I just run the frontend without the backend? or do i need to to run that as well?
let me know if we need to follow any extra steps 
ty
![image](https://github.com/user-attachments/assets/5d34a364-64df-4d67-8be1-33e12be35a65)

**Comment by priyam-03** [comment]
yeah @RohithNair27 you can work on this issue
the profile image that is displayed beside Jobs section clicking on that a popup will come where will be two option go to profile and logout , profile will redirect to profile page and logout will do its own functionality
and remove logout from the current position.

**Comment by priyam-03** [comment]
If any doubt occurs you can mail me.

**Comment by RohithNair27** [comment]
![image](https://github.com/user-attachments/assets/afacde85-e4dd-4085-a6a6-c1ab96edce67)

Hi @priyam-03 
did you accept any pull request recently?? I am unable to login in smaller screen

The screen is not responsive

**Comment by priyam-03** [comment]
> ![image](https://github.com/user-attachments/assets/afacde85-e4dd-4085-a6a6-c1ab96edce67)
> 
> Hi @priyam-03 
> did you accept any pull request recently?? I am unable to login in smaller screen
> 
> The screen is not responsive
> 
> 
> 
> 

Yes , okay let me check

**Comment by priyam-03** [comment]
Is it in localhost or in deployed version?

**Comment by RohithNair27** [comment]
deployed one, I have two laptops and in the smaller one the issue is there 
the page is not responsive

**Comment by priyam-03** [comment]
Okay @RohithNair27  can you resolve it by a different pull request ,
also like login screen you can add a Register Text above that.

**Comment by RohithNair27** [comment]
Ok let me create another issue for that

**Comment by priyam-03** [comment]
Hey @RohithNair27 this issue is already resolved by a core member, you may add another pull request by enhancing that otherwise you can work on this this issues [#27](https://github.com/priyam-03/Recruitify/issues/27) or #58 
If you are interested I will assign those to you.

**Comment by RohithNair27** [comment]
Hey @priyam-03, Not a problem
Already working on #54, will complete this and take a new one

**Comment by priyam-03** [comment]
That's great @RohithNair27.
