### ISSUE TITLE
Sign up and register page not responsive for smaller devices 

### ISSUE THREAD

**Issue by RohithNair27** [priyam-03/Recruitify#54]
Hi @priyam-03 
As discussed, the sign up and register page is not responsive for smaller devices

Kindly assign this issue to me and tag as hacktober

**Comment by priyam-03** [comment]
1. Make it responsive 
2. Add Register Text like Login
3. There is some irregularities in text box width resolve that also.

**Comment by RohithNair27** [comment]
OK @priyam-03 ,
Will try to revamp both the pages
