### ISSUE TITLE
 Beautification of Post Module UI

### ISSUE THREAD

**Issue by priyam-03** [priyam-03/Recruitify#58]
**Description**  
The current post module requires enhanced styling for a more modern, clean, and visually appealing UI that integrates seamlessly with the rest of the website's design. This update should improve user experience, readability, and accessibility across the module.

**Current Observations**
1. The layout and color palette could be updated to align better with our site’s overall theme.
2. Icons and buttons lack hover animations, shadow effects, and distinct styling to improve interactivity.
3. Text sections, images, and comments could use additional spacing, padding, and/or alignment tweaks to improve visual hierarchy.

![image](https://github.com/user-attachments/assets/065b0be7-95c0-4722-a7e5-8c0ec0f7439e)

**Suggested Improvements (Open to Ideas)**
- **Color Palette**: Update the color scheme to match our brand colors and improve contrast. Consider using soft background gradients or borders to differentiate sections.
- **Typography**: Adjust font sizes and weights for headings and body text, ensuring legibility and consistency with the rest of the site.
- **Buttons and Icons**:
  - Add hover effects (e.g., color changes, text decoration, or slight scale increase).
  - Use subtle shadows for better contrast on dark backgrounds.
  - Distinguish "Like," "Dislike," and "Comment" icons with clearer active and inactive states.
- **Images**: Adjust image sizes for uniformity, add subtle borders, and apply rounded corners for a cleaner look.
- **Animations**: Consider smooth animations for showing/hiding comments or toggling text sections for a dynamic feel.

**Additional Notes**
1. Ensure all changes are responsive and accessible.
2. Maintain code modularity by updating only the necessary components. (You may use .module.css)

**Expected Outcome**  
A visually enhanced and cohesive post module that integrates seamlessly with the rest of the website, providing a user-friendly and aesthetically pleasing experience.

https://github.com/priyam-03/Recruitify/blob/main/frontend/src/shared/components/AllPosts.js
https://github.com/priyam-03/Recruitify/blob/main/frontend/src/User/myPosts.js
https://github.com/priyam-03/Recruitify/blob/main/frontend/src/styles/posts.css

**Comment by aniruddhaadak80** [comment]
Please assign this issue . I am working on this .

**Comment by aniruddhaadak80** [comment]
Please check this update in AllPosts.js and myPosts.js #60

**Comment by priyam-03** [comment]
@aniruddhaadak80 but the  issue was regarding handling the styles (mainly the css part).
